let current=new Date(2026,7,16);
const cal=document.getElementById("calendar"),agenda=document.getElementById("agenda"),sheet=document.getElementById("sheet"),sheetContent=document.getElementById("sheetContent");
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const parse=s=>{let[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c)};
const status=d=>HOLIDAYS[iso(d)]?{holiday:true,reason:HOLIDAYS[iso(d)]}:DAY_ORDER_BY_DATE[iso(d)]?{working:true,day:DAY_ORDER_BY_DATE[iso(d)]}:{};
const events=d=>status(d).working?(TIMETABLE[status(d).day]||[]):[];
const bg=s=>s.holiday?"holidaybg":`d${s.day}bg`;const dow=["SUN","MON","TUE","WED","THU","FRI","SAT"];
function render(){document.getElementById("monthTitle").textContent=current.toLocaleDateString("en-IN",{month:"long",year:"numeric"});document.getElementById("todayLabel").textContent=new Date().toLocaleDateString("en-IN",{weekday:"long"});renderMonth()}
function renderMonth(){cal.className="calendar";agenda.className="hidden";let first=new Date(current.getFullYear(),current.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());let html=dow.map(x=>`<div class="weekday">${x}</div>`).join("");
for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i),s=status(d),tod=iso(d)===iso(new Date());let content=`<div class="numline"><span class="num">${d.getDate()}</span>${s.working?`<span class="order">D${s.day}</span>`:""}</div>`;if(s.holiday)content+=`<div class="holidayText">${s.reason}</div>`;else if(s.working)content+=`<div class="count">${events(d).length} ${events(d).length===1?"class":"classes"}</div>`;else content+=`<div class="count">NO CLASSES</div>`;html+=`<div class="cell ${bg(s)} ${d.getMonth()!==current.getMonth()?"muted":""} ${tod?"todayCell":""}" data-date="${iso(d)}">${content}</div>`}cal.innerHTML=html;document.querySelectorAll(".cell").forEach(x=>x.onclick=()=>openDay(parse(x.dataset.date)))}
function openDay(d){current=d;let s=status(d),dt=d.toLocaleDateString("en-IN",{weekday:"long",month:"long",day:"numeric",year:"numeric"});let html=`<div class="sheetDate">${dt}</div><div class="sheetTitle">${s.holiday?"Holiday":s.working?"Day "+s.day:"No Class"}</div>`;if(s.holiday)html+=`<div class="noClass">${s.reason}<br><br>No classes today — enjoy the holiday.</div>`;else if(!s.working)html+=`<div class="noClass">No classes scheduled.</div>`;else{let ev=events(d);html+=ev.length?ev.map(x=>`<div class="classCard ${x.type==="LAB"?"lab":"lecture"}"><span class="badge">${x.type==="LAB"?"LAB":"LECTURE"}</span><div class="classTime">${x.time}</div><div class="className">${x.subject}</div><div class="classMeta">${x.location}</div></div>`).join(""):`<div class="noClass">No classes scheduled.</div>`}sheetContent.innerHTML=html;sheet.classList.remove("hidden")}
function renderAgenda(){cal.className="hidden";agenda.className="agenda";let html="";let start=new Date(current.getFullYear(),current.getMonth(),1),end=new Date(current.getFullYear(),current.getMonth()+1,0);for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){let s=status(d);if(!s.working&&!s.holiday)continue;html+=`<div class="agendaDay"><small>${d.toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long"})}</small><h3>${s.holiday?"Holiday":"Day "+s.day}</h3>`;if(s.holiday)html+=`<div class="agendaItem">${s.reason}</div>`;else events(d).forEach(x=>html+=`<div class="agendaItem"><b>${x.time} — ${x.subject}</b><span>${x.type} • ${x.location}</span></div>`);html+="</div>"}agenda.innerHTML=html}
document.getElementById("prev").onclick=()=>{current.setMonth(current.getMonth()-1);render()};document.getElementById("next").onclick=()=>{current.setMonth(current.getMonth()+1);render()};document.getElementById("today").onclick=()=>{current=new Date();render()};
document.getElementById("monthBtn").onclick=()=>{document.getElementById("monthBtn").classList.add("active");document.getElementById("agendaBtn").classList.remove("active");renderMonth()};document.getElementById("agendaBtn").onclick=()=>{document.getElementById("agendaBtn").classList.add("active");document.getElementById("monthBtn").classList.remove("active");renderAgenda()};document.getElementById("closeSheet").onclick=()=>sheet.classList.add("hidden");sheet.onclick=e=>{if(e.target===sheet)sheet.classList.add("hidden")};render();